[package]
name = "prok-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "prok"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
prok-core = { path = "../prok-core" }
rayon = "1"

[lints]
workspace = true
